'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'zh' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  zh: {
    // Header
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '我们的服务',
    'nav.projects': '经典业绩',
    'nav.contact': '联系我们',
    'nav.careers': '加入我们',

    // Hero
    'hero.title': '易佳瑞能源',
    'hero.subtitle': '专业的新能源设备监理服务',
    'hero.learn_more': '了解服务',
    'hero.contact_us': '联系我们',
    'hero.years_experience': '年行业经验',
    'hero.projects': '项目案例',
    'hero.partners': '合作伙伴',
    'hero.qualification': '监理资质',
    'hero.scroll_hint': '向下滚动',
    'hero.description': '我们致力于为新能源行业提供专业、可靠的设备监理服务，确保项目质量与安全',
    'hero.cta_primary': '联系我们',
    'hero.cta_secondary': '了解更多',

    // About
    'about.title': '关于我们',
    'about.description': '北京易佳瑞能源技术服务有限公司成立于2014年，专注于新能源电力行业技术服务',
    'about.company_intro': '企业简介',
    'about.company_desc': '北京易佳瑞能源技术服务有限公司成立于2014年，是一家专注于新能源电力行业的技术服务企业。业务范围覆盖风力发电、光伏发电、储能等新能源电力领域。致力为广大客户提供驻厂监造、第三方检验、风机基础技术支持等质量控制服务和新能源场站建模及涉网设备检测等技术服务。',
    'about.years_experience': '年行业经验',
    'about.projects_completed': '完成项目',
    'about.mission_title': '我们的使命',
    'about.mission_desc': '为新能源行业提供专业、可靠的设备监理服务，确保项目质量与安全',
    'about.vision_title': '我们的愿景',
    'about.vision_desc': '成为新能源电力行业技术服务的领军企业，推动行业健康发展',
    'about.values_title': '我们的价值观',
    'about.values_desc': '专业、诚信、创新、服务，以客户需求为导向，持续创造价值',
    'about.company_desc_1': '北京易佳瑞能源技术服务有限公司成立于2014年，是一家专注于新能源电力行业的技术服务企业。',
    'about.company_desc_2': '业务范围覆盖风力发电、光伏发电、储能等新能源电力领域。致力为广大客户提供驻厂监造、第三方检验、风机基础技术支持等质量控制服务和新能源场站建模及涉网设备检测等技术服务。',
    'about.company_desc_3': '经过10余年的发展，积累了大量及丰富的检验检测及项目服务经验，建立了完整的技术能力和运作管理体系。公司具有ISO9001质量管理，ISO14001环境管理和ISO45001职业健康安全管理体系认证证书。公司是中国设备监理协会会员单位，具有中国设备监理单位甲级资质。',
    'about.stat_founded': '成立年份',
    'about.stat_business': '项目协作系统',
    'about.stat_qualification': '监理资质',
    'about.stat_business_number': '自研',
    'about.stat_qualification_level': '甲级',
    'about.stat_certification': '体系认证',
    'about.click_to_view': '点击查看详情',
    'about.cert_system_title': '自研项目协作系统',
    'about.cert_qualification_title': '甲级监理资质',
    'about.cert_iso_title': 'ISO体系认证',
    'about.cert_system1': '系统截图1',
    'about.cert_system2': '系统截图2',
    'about.cert_qualification1': '中国设备监理甲级资质',
    'about.cert_iso1': 'ISO9001质量管理认证证书',
    'about.cert_iso2': 'IS014001环境管理体系认证证书',
    'about.cert_iso3': 'ISO18001职业健康安全管理体系认证证书',
    'about.gallery_title': '企业风采',
    'about.gallery_team': '专业团队现场服务',
    'about.gallery_equipment': '精密设备检测',
    'about.gallery_meeting': '项目技术交流',
    'about.gallery_certificates': '权威资质认证',
    'about.certificates_title': '资质证书',
    'about.certificates_desc': '权威认证，专业保障，值得信赖的技术实力',
    'about.advantages': '我们的优势',
    'about.advantage_tech_title': '技术实力',
    'about.advantage_tech_desc': '自主研发的项目协作管理系统，拥有多项知识产权，助力客户优化质量与成本管理。',
    'about.advantage_qual_title': '专业资质',
    'about.advantage_qual_desc': '风力发电与光伏发电设备监理甲级资质，以及ISO9001、ISO14001、ISO45001等权威认证。',
    'about.advantage_exp_title': '行业经验',
    'about.advantage_exp_desc': '十余年项目积累，与国内外多家知名能源企业建立了长期合作关系。',
    'about.advantage_vision_title': '绿色愿景',
    'about.advantage_vision_desc': '以创新为驱动，以专业为基础，为新能源电力发展提供强有力的技术支持。',

    // Services
    'services.title': '我们的服务',
    'services.subtitle': '北京易佳瑞能源技术服务有限公司专注于新能源电力项目各阶段技术服务',
    'services.manufacturing_title': '设备监造和质量控制',
    'services.manufacturing_1': '风力发电设备监造',
    'services.manufacturing_2': '光伏发电设备监造',
    'services.manufacturing_3': '储能电站设备监造',
    'services.manufacturing_4': '设备关键点见证与出厂检验',
    'services.construction_title': '建设现场服务',
    'services.construction_1': '风机基础技术服务',
    'services.construction_2': '场站建模及涉网设备检测',
    'services.construction_3': '现场施工安全服务',
    'services.operation_title': '运行维护与优化',
    'services.operation_1': '在役设备检测与维护',
    'services.operation_2': '发电量分析与技术改造',
    'services.operation_3': '增效升级解决方案',
    'services.feature_title': '服务特色',
    'services.feature_custom_title': '定制化服务',
    'services.feature_custom_desc': '根据客户需求，提供精准、高效的技术解决方案。',
    'services.feature_lifecycle_title': '全生命周期支持',
    'services.feature_lifecycle_desc': '覆盖从规划到运行维护的每个环节。',
    'services.feature_team_title': '专业团队保障',
    'services.feature_team_desc': '技术专家与项目经理团队全程陪伴，确保项目顺利完成。',
    'services.cta_title': '需要专业的新能源技术服务？',
    'services.cta_desc': '联系我们，获取定制化的技术解决方案',
    'services.cta_button': '立即咨询',
    'services.scenarios_title': '服务场景',
    'services.scenarios_desc': '专业的服务团队，覆盖项目全生命周期的技术支持',
    'services.scenario_manufacturing': '设备监造',
    'services.scenario_manufacturing_desc': '制造过程质量监督',
    'services.scenario_construction': '现场服务',
    'services.scenario_construction_desc': '建设期技术支持',
    'services.scenario_operation': '运维服务',
    'services.scenario_operation_desc': '设备运行维护',

    // Projects
    'projects.title': '经典业绩',
    'projects.wind_title': '风电项目业绩',
    'projects.wind_1': '三塘湖1000MW风力发电项目',
    'projects.wind_2': '凤台县尚塘200MW风力发电项目',
    'projects.wind_3': '阜新新德200MW风力发电项目',
    'projects.wind_4': '清河300MW风力发电项目',
    'projects.solar_title': '光伏项目案例',
    'projects.solar_1': '盈江县111MW农业光伏发电项目',
    'projects.solar_2': '宜良新发120MW药光互补光伏发电',
    'projects.solar_3': '唐河县200MW光伏发电项目',
    'projects.solar_4': '承德丰宁丰晟100MW农光互补项目',
    'projects.testimonials_title': '客户评价',
    'projects.testimonial_1': '易佳瑞团队的专业性和执行力让我们深感信赖，他们的技术支持为项目的成功实施提供了坚实保障。',
    'projects.testimonial_1_author': '华润电力项目负责人',
    'projects.testimonial_2': '从规划到维护，易佳瑞始终以客户为中心，提供了高效、专业的服务。',
    'projects.testimonial_2_author': '金风科技合作伙伴',
    'projects.partners_title': '合作伙伴',
    'projects.partners_desc': '我们与以下知名企业保持长期合作关系：',
    'projects.gallery_title': '项目实景',
    'projects.gallery_desc': '真实的项目案例，展现我们的专业实力与丰富经验',
    'projects.gallery_wind_farm': '风电场全景',
    'projects.gallery_wind_inspection': '设备质量检测',
    'projects.gallery_solar_plant': '光伏电站',
    'projects.gallery_solar_installation': '安装质量监督',
    'projects.gallery_energy_storage': '储能系统',
    'projects.gallery_completion': '项目交付',
    'projects.category_wind': '风电',
    'projects.category_solar': '光伏',
    'projects.category_storage': '储能',
    'projects.category_completion': '验收',

    // Contact
    'contact.title': '联系我们',
    'contact.subtitle': '欢迎联系我们，获取专业的新能源技术服务',
    'contact.info_title': '联系信息',
    'contact.address_title': '公司地址',
    'contact.address': '北京市海淀区马甸东路19号金澳国际B座26层2615室',
    'contact.phone_title': '联系电话',
    'contact.email_title': '电子邮箱',
    'contact.website_title': '公司网站',
    'contact.wechat_title': '微信公众号',
    'contact.wechat_desc': '扫码关注获取更多资讯',
    'contact.wechat_scan_tip': '使用微信扫描二维码关注我们',
    'contact.hours_title': '营业时间',
    'contact.hours_weekday': '周一 - 周五',
    'contact.hours_saturday': '周六',
    'contact.hours_sunday': '周日',
    'contact.hours_closed': '休息',
    'contact.form_title': '在线咨询',
    'contact.form_name': '姓名',
    'contact.form_phone': '电话',
    'contact.form_email': '邮箱',
    'contact.form_company': '公司名称',
    'contact.form_message': '咨询内容',
    'contact.form_name_placeholder': '请输入您的姓名',
    'contact.form_phone_placeholder': '请输入您的电话',
    'contact.form_email_placeholder': '请输入您的邮箱',
    'contact.form_company_placeholder': '请输入您的公司名称',
    'contact.form_message_placeholder': '请详细描述您的需求或问题',
    'contact.form_submit': '提交咨询',
    'contact.form_required': '*',
    'contact.get_in_touch': '联系方式',
    'contact.send_message': '发送消息',
    'contact.company_name': '北京易佳瑞能源技术服务有限公司',
    'contact.business_scope': '专注于新能源电力行业技术服务',
    'contact.service_area': '业务覆盖风力发电、光伏发电、储能等领域',

    // Footer
    'footer.company_desc': '北京易佳瑞能源技术服务有限公司成立于2014年，专注于新能源电力行业的技术服务，致力为客户提供专业的质量控制服务和技术支持。',
    'footer.quick_links': '快速链接',
    'footer.contact_info': '联系方式',
    'footer.copyright': '© 2024 北京易佳瑞能源技术服务有限公司. 保留所有权利. 京ICP备2024098432号-1',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.sitemap': '网站地图',
    'footer.careers_title': '加入我们',
    'footer.careers_desc': '我们正在寻找有才华的专业人士加入我们的团队，共同推动新能源行业的发展',
    'footer.careers_button': '发送简历',

    // Careers
    'careers.job_title': '塔筒监理工程师',
    'careers.job_type_fulltime': '全职',
    'careers.job_education': '本科及以上',
    'careers.job_experience': '1年以上经验',
    'careers.job_responsibilities': '【岗位职责】',
    'careers.job_requirements': '【任职要求】',
    'careers.responsibility_1': '根据客户技术文件及相关标准，从事塔筒检验',
    'careers.responsibility_2': '负责审查设备制造厂质量管理体系，审查设备制造质量计划、检验大纲/规程、完工报告等文件',
    'careers.responsibility_3': '负责与工厂的沟通协调，在发现问题后及时向上级汇报并跟进处理',
    'careers.responsibility_4': '负责对监造过程中发现的问题采取相应措施，跟踪并验证处理结果',
    'careers.responsibility_5': '根据监造大纲编辑监造细则，质量监督过程中按照公司要求及时建立日报、日志、周报等过程资料',
    'careers.responsibility_6': '完成领导安排的其它工作',
    'careers.requirement_1': '本科以上学历，机械、材料、电气或自动化相关专业',
    'careers.requirement_2': '1年以上相关产品检验、监造等经验优先',
    'careers.requirement_3': '熟悉设备制造标准规范、相关规程以及监造工作流程',
    'careers.requirement_4': '具备良好的沟通能力、团队合作能力、解决问题能力',
    'careers.requirement_5': '持有专业设备监理、设备监理职业资格、中级职称等证书优先',
    'careers.requirement_6': '能适应长期出差性质工作',
    'careers.location': '北京市海淀区',
    'careers.publish_date': '发布时间：2024年1月',
    'careers.no_suitable_position': '没有找到合适的职位？',
    'careers.general_application': '我们随时欢迎优秀的人才加入我们的团队。请将您的简历发送给我们，我们会在有合适机会时联系您。',
    'careers.submit_resume': '投递简历',
    'careers.phone_consultation': '电话咨询',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Our Services',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'nav.careers': 'Careers',

    // Hero
    'hero.title': 'Yijiarui Energy',
    'hero.subtitle': 'Professional New Energy Equipment Supervision Services',
    'hero.learn_more': 'Learn More',
    'hero.contact_us': 'Contact Us',
    'hero.years_experience': 'Years Experience',
    'hero.projects': 'Projects',
    'hero.partners': 'Partners',
    'hero.qualification': 'Grade A Qualification',
    'hero.scroll_hint': 'Scroll Down',
    'hero.description': 'We are committed to providing professional and reliable equipment supervision services for the new energy industry, ensuring project quality and safety',
    'hero.cta_primary': 'Contact Us',
    'hero.cta_secondary': 'Learn More',

    // About
    'about.title': 'About Us',
    'about.description': 'Beijing Yijiarui Energy Technology Service Co., Ltd. was established in 2014, specializing in technical services for the new energy power industry',
    'about.company_intro': 'Company Introduction',
    'about.company_desc': 'Beijing Yijiarui Energy Technology Service Co., Ltd. was established in 2014, specializing in technical services for the new energy power industry. Our business covers wind power, photovoltaic power generation, energy storage and other new energy power fields. We are committed to providing customers with quality control services such as on-site supervision, third-party inspection, wind turbine foundation technical support, and technical services such as new energy station modeling and grid-connected equipment testing.',
    'about.years_experience': 'Years Experience',
    'about.projects_completed': 'Projects Completed',
    'about.mission_title': 'Our Mission',
    'about.mission_desc': 'To provide professional and reliable equipment supervision services for the new energy industry, ensuring project quality and safety',
    'about.vision_title': 'Our Vision',
    'about.vision_desc': 'To become a leading enterprise in technical services for the new energy power industry and promote healthy industry development',
    'about.values_title': 'Our Values',
    'about.values_desc': 'Professionalism, integrity, innovation, and service, customer-oriented, continuously creating value',
    'about.company_desc_1': 'Beijing Yijiarui Energy Technology Service Co., Ltd. was established in 2014, specializing in technical services for the new energy power industry.',
    'about.company_desc_2': 'Our business covers wind power, photovoltaic power generation, energy storage and other new energy power fields. We are committed to providing customers with quality control services such as on-site supervision, third-party inspection, wind turbine foundation technical support, and technical services such as new energy station modeling and grid-connected equipment testing.',
    'about.company_desc_3': 'After more than 10 years of development, we have accumulated extensive experience in inspection, testing and project services, and established a complete technical capability and operational management system. The company has ISO9001 quality management, ISO14001 environmental management and ISO45001 occupational health and safety management system certification. The company is a member of China Equipment Supervision Association and has Grade A qualification for equipment supervision.',
    'about.stat_founded': 'Founded',
    'about.stat_business': 'Project Collaboration System',
    'about.stat_qualification': 'Grade A Qualification',
    'about.stat_business_number': 'Self-developed',
    'about.stat_qualification_level': 'Grade A',
    'about.stat_certification': 'System Certification',
    'about.click_to_view': 'Click to view details',
    'about.cert_system_title': 'Self-developed Project Collaboration System',
    'about.cert_qualification_title': 'Grade A Supervision Qualification',
    'about.cert_iso_title': 'ISO System Certification',
    'about.cert_system1': 'System Screenshot 1',
    'about.cert_system2': 'System Screenshot 2',
    'about.cert_qualification1': 'China Equipment Supervision Grade A Qualification',
    'about.cert_iso1': 'ISO9001 Quality Management Certification',
    'about.cert_iso2': 'ISO14001 Environmental Management System Certification',
    'about.cert_iso3': 'ISO18001 Occupational Health and Safety Management System Certification',
    'about.gallery_title': 'Company Gallery',
    'about.gallery_team': 'Professional Team On-site Service',
    'about.gallery_equipment': 'Precision Equipment Testing',
    'about.gallery_meeting': 'Project Technical Communication',
    'about.gallery_certificates': 'Authoritative Qualification Certification',
    'about.certificates_title': 'Certificates',
    'about.certificates_desc': 'Authoritative certification, professional guarantee, trustworthy technical strength',
    'about.advantages': 'Our Advantages',
    'about.advantage_tech_title': 'Technical Strength',
    'about.advantage_tech_desc': 'Self-developed Project collaboration management system with multiple intellectual property rights, helping customers optimize quality and cost management.',
    'about.advantage_qual_title': 'Professional Qualifications',
    'about.advantage_qual_desc': 'Grade A qualification for wind power and photovoltaic power generation equipment supervision, as well as authoritative certifications such as ISO9001, ISO14001, and ISO45001.',
    'about.advantage_exp_title': 'Industry Experience',
    'about.advantage_exp_desc': 'More than ten years of project accumulation, establishing long-term cooperative relationships with many well-known domestic and international energy companies.',
    'about.advantage_vision_title': 'Green Vision',
    'about.advantage_vision_desc': 'Driven by innovation and based on professionalism, providing strong technical support for new energy power development.',

    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Beijing Yijiarui Energy Technology Service Co., Ltd. focuses on technical services for all stages of new energy power projects',
    'services.manufacturing_title': 'Equipment Manufacturing Supervision and Quality Control',
    'services.manufacturing_1': 'Wind power equipment manufacturing supervision',
    'services.manufacturing_2': 'Photovoltaic power equipment manufacturing supervision',
    'services.manufacturing_3': 'Energy storage power station equipment manufacturing supervision',
    'services.manufacturing_4': 'Equipment key point witnessing and factory inspection',
    'services.construction_title': 'Construction Site Services',
    'services.construction_1': 'Wind turbine foundation technical services',
    'services.construction_2': 'Station modeling and grid-connected equipment testing',
    'services.construction_3': 'On-site construction safety services',
    'services.operation_title': 'Operation, Maintenance and Optimization',
    'services.operation_1': 'In-service equipment inspection and maintenance',
    'services.operation_2': 'Power generation analysis and technical transformation',
    'services.operation_3': 'Efficiency improvement and upgrade solutions',
    'services.feature_title': 'Service Features',
    'services.feature_custom_title': 'Customized Services',
    'services.feature_custom_desc': 'Provide precise and efficient technical solutions according to customer needs.',
    'services.feature_lifecycle_title': 'Full Lifecycle Support',
    'services.feature_lifecycle_desc': 'Covering every aspect from planning to operation and maintenance.',
    'services.feature_team_title': 'Professional Team Guarantee',
    'services.feature_team_desc': 'Technical experts and project manager teams accompany the entire process to ensure successful project completion.',
    'services.cta_title': 'Need Professional New Energy Technical Services?',
    'services.cta_desc': 'Contact us for customized technical solutions',
    'services.cta_button': 'Consult Now',
    'services.scenarios_title': 'Service Scenarios',
    'services.scenarios_desc': 'Professional service team covering technical support throughout the project lifecycle',
    'services.scenario_manufacturing': 'Equipment Supervision',
    'services.scenario_manufacturing_desc': 'Manufacturing Process Quality Supervision',
    'services.scenario_construction': 'On-site Service',
    'services.scenario_construction_desc': 'Construction Period Technical Support',
    'services.scenario_operation': 'O&M Service',
    'services.scenario_operation_desc': 'Equipment Operation and Maintenance',

    // Projects
    'projects.title': 'Classic Projects',
    'projects.wind_title': 'Wind Power Project Performance',
    'projects.wind_1': 'Santanghu 1000MW Wind Power Project',
    'projects.wind_2': 'Fengtai County Shangtang 200MW Wind Power Project',
    'projects.wind_3': 'Fuxin Xinde 200MW Wind Power Project',
    'projects.wind_4': 'Qinghe 300MW Wind Power Project',
    'projects.solar_title': 'Solar Project Cases',
    'projects.solar_1': 'Yingjiang County 111MW Agri-PV Project',
    'projects.solar_2': 'Yiliang Xinfa 120MW Medicine-PV Complementary Project',
    'projects.solar_3': 'Tanghe County 200MW Solar Power Project',
    'projects.solar_4': 'Chengde Fengning Fengsheng 100MW Agri-PV Complementary Project',
    'projects.testimonials_title': 'Client Testimonials',
    'projects.testimonial_1': 'We deeply trust the professionalism and execution of the Yijiarui team. Their technical support provides a solid guarantee for the successful implementation of our projects.',
    'projects.testimonial_1_author': 'China Resources Power Project Manager',
    'projects.testimonial_2': 'From planning to maintenance, Yijiarui always puts customers first and provides efficient and professional services.',
    'projects.testimonial_2_author': 'Goldwind Technology Partner',
    'projects.partners_title': 'Partners',
    'projects.partners_desc': 'We maintain long-term cooperative relationships with the following well-known companies:',
    'projects.gallery_title': 'Project Gallery',
    'projects.gallery_desc': 'Real project cases showcasing our professional strength and rich experience',
    'projects.gallery_wind_farm': 'Wind Farm Overview',
    'projects.gallery_wind_inspection': 'Equipment Quality Testing',
    'projects.gallery_solar_plant': 'Solar Power Plant',
    'projects.gallery_solar_installation': 'Installation Quality Supervision',
    'projects.gallery_energy_storage': 'Energy Storage System',
    'projects.gallery_completion': 'Project Delivery',
    'projects.category_wind': 'Wind Power',
    'projects.category_solar': 'Solar Power',
    'projects.category_storage': 'Energy Storage',
    'projects.category_completion': 'Acceptance',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Welcome to contact us for professional new energy technical services',
    'contact.info_title': 'Contact Information',
    'contact.address_title': 'Company Address',
    'contact.address': 'Room 2615, 26th Floor, Block B, Jinao International, No. 19 Madian East Road, Haidian District, Beijing',
    'contact.phone_title': 'Phone',
    'contact.email_title': 'Email',
    'contact.website_title': 'Website',
    'contact.wechat_title': 'WeChat Official Account',
    'contact.wechat_desc': 'Scan QR code for more information',
    'contact.wechat_scan_tip': 'Scan QR code with WeChat to follow us',
    'contact.hours_title': 'Business Hours',
    'contact.hours_weekday': 'Monday - Friday',
    'contact.hours_saturday': 'Saturday',
    'contact.hours_sunday': 'Sunday',
    'contact.hours_closed': 'Closed',
    'contact.form_title': 'Online Consultation',
    'contact.form_name': 'Name',
    'contact.form_phone': 'Phone',
    'contact.form_email': 'Email',
    'contact.form_company': 'Company',
    'contact.form_message': 'Message',
    'contact.form_name_placeholder': 'Please enter your name',
    'contact.form_phone_placeholder': 'Please enter your phone number',
    'contact.form_email_placeholder': 'Please enter your email',
    'contact.form_company_placeholder': 'Please enter your company name',
    'contact.form_message_placeholder': 'Please describe your needs or questions in detail',
    'contact.form_submit': 'Submit Inquiry',
    'contact.form_required': '*',
    'contact.get_in_touch': 'Get In Touch',
    'contact.send_message': 'Send Message',
    'contact.company_name': 'Beijing Yijiarui Energy Technology Service Co., Ltd.',
    'contact.business_scope': 'Specializing in technical services for the new energy power industry',
    'contact.service_area': 'Business covers wind power, photovoltaic power generation, energy storage and other fields',

    // Footer
    'footer.company_desc': 'Beijing Yijiarui Energy Technology Service Co., Ltd. was established in 2014, specializing in technical services for the new energy power industry, committed to providing customers with professional quality control services and technical support.',
    'footer.quick_links': 'Quick Links',
    'footer.contact_info': 'Contact Information',
    'footer.copyright': '© 2024 Beijing Yijiarui Energy Technology Service Co., Ltd. All rights reserved. 京ICP备2024098432号-1',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.sitemap': 'Site Map',
    'footer.careers_title': 'Join Us',
    'footer.careers_desc': 'We are looking for talented professionals to join our team and promote the development of the new energy industry together',
    'footer.careers_button': 'Send Resume',

    // Careers
    'careers.job_title': 'Tower Supervision Engineer',
    'careers.job_type_fulltime': 'Full-time',
    'careers.job_education': 'Bachelor\'s Degree or Above',
    'careers.job_experience': '1+ Years Experience',
    'careers.job_responsibilities': 'Job Responsibilities',
    'careers.job_requirements': 'Job Requirements',
    'careers.responsibility_1': 'Conduct tower inspection according to customer technical documents and relevant standards',
    'careers.responsibility_2': 'Review equipment manufacturer quality management systems, manufacturing quality plans, inspection outlines/procedures, and completion reports',
    'careers.responsibility_3': 'Coordinate with factories, report issues to supervisors promptly and follow up on resolution',
    'careers.responsibility_4': 'Take appropriate measures for issues found during supervision and track verification of results',
    'careers.responsibility_5': 'Prepare supervision guidelines based on supervision outlines, establish daily reports, logs, weekly reports and other process materials according to company requirements',
    'careers.responsibility_6': 'Complete other tasks assigned by leadership',
    'careers.requirement_1': 'Bachelor\'s degree or above in Mechanical, Materials, Electrical or Automation related majors',
    'careers.requirement_2': 'Preference for 1+ years of experience in related product inspection and supervision',
    'careers.requirement_3': 'Familiar with equipment manufacturing standards, regulations and supervision workflows',
    'careers.requirement_4': 'Good communication, teamwork and problem-solving skills',
    'careers.requirement_5': 'Preference for professional equipment supervision qualifications, intermediate titles or related certificates',
    'careers.requirement_6': 'Ability to adapt to long-term business travel',
    'careers.location': 'Haidian District, Beijing',
    'careers.publish_date': 'Published: January 2024',
    'careers.no_suitable_position': 'Can\'t find a suitable position?',
    'careers.general_application': 'We welcome talented individuals to join our team at any time. Please send us your resume and we will contact you when suitable opportunities arise.',
    'careers.submit_resume': 'Submit Resume',
    'careers.phone_consultation': 'Phone Consultation',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh')

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language
      if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'en')) {
        setLanguage(savedLanguage)
      }
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang)
    }
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
